# Generated by Django 4.1.2 on 2022-10-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='slate',
            new_name='state',
        ),
    ]
